"""`coach memory check` (E3-6, E3-8): validate the memory folder and compare it with the data.

Levels: ``error`` (the file is invalid or says something impossible: exit 1), ``warning`` (probably wrong or
outdated), ``info`` (a fact is simply missing). Everything that needs the database is skipped when none is given.
"""
from __future__ import annotations

import datetime as dt
import re
import statistics
from collections import Counter
from typing import Optional

from coach.memory import qgen, txmatch
from coach.memory.store import MemoryStore, Issue, extra_fields

LEVELS = {"error": 0, "warning": 1, "info": 2}
SHARE_WARN = 0.20            # an annotation matching more than this share of an account's transactions
MIN_ACCOUNT_TX = 30          # ... only judged on accounts with at least this many transactions
AMOUNT_TOLERANCE = 0.10


def summarize(issues: list[Issue]) -> dict:
    c = Counter(i.level for i in issues)
    by_code = Counter(i.code for i in issues)
    return {"errors": c["error"], "warnings": c["warning"], "info": c["info"], "by_code": dict(by_code)}


def _regex_hits(pattern: str, txs: list[dict], keys=True, desc=True) -> list[dict]:
    try:
        rx = re.compile(pattern, re.I)
    except re.error:
        return []
    return [t for t in txs if (desc and rx.search(t["desc"] or "")) or (keys and rx.search(t["key"] or ""))]


def _loan_schedule_checks(add, rel, m, today) -> None:
    """E9: the schedule computed from the file against what the same file declares (capital due, instalment); a lease without an end date."""
    from coach.loans import schedule as loan_schedule
    if m.kind in ("loa", "lld"):
        if m.end_date is None:
            add("info", "lease_end_missing", rel, "no end_date: the end-of-contract reminders (buy or return, mileage) need it", "end_date")
        return
    sch = loan_schedule.compute(m, today)
    if sch.status != "computed":
        return
    if sch.outstanding_check:
        c = sch.outstanding_check
        add("info", "schedule_capital_differs", rel,
            f"the amortization schedule gives {c['computed']} EUR due on {c['as_of']} but outstanding is {c['declared']} EUR: the rate, the "
            "term, a deferral or an early repayment in the file may not match the contract", "outstanding")
    pc = sch.payment_check
    if pc and pc["status"] == "differs":
        add("info", "schedule_payment_differs", rel,
            f"the schedule gives an instalment of {pc['computed_total']} EUR (insurance included) but monthly_payment is {pc['declared']} EUR "
            "(variable rate, modulation, fees, or a figure to check)", "monthly_payment")


def run_check(store: MemoryStore, con=None, *, stale_months: int = 6, asset_stale_months: int = 3,
              today: Optional[dt.date] = None, cfg=None) -> list[Issue]:
    today = today or dt.date.today()
    out: list[Issue] = []
    add = lambda *a, **k: out.append(Issue(*a, **k))        # noqa: E731

    # ---- 0. symlinks that lead out of the folder are never followed
    for rel in store.escaping_symlinks():
        add("error", "symlink_outside", rel, "is a symlink to a file outside the memory folder: it is not read or written "
            "(replace it with a real file or a link inside memory/)")

    # ---- 1. schema of every file
    bad_files = set()
    for rel in store.files():
        if store.kind_of(rel) != "yaml":
            continue
        model, issues = store.validate_text(rel, store.read_text(rel))
        out += issues
        if issues:
            bad_files.add(rel)
            continue
        for extra in extra_fields(model):
            add("info", "unknown_field", rel, f"field {extra!r} is not part of the schema (kept as is)", extra)

    # ---- 2. the Markdown view of the questions
    md = store.read_text("open-questions.md")
    if store.exists("open-questions.yaml") and "open-questions.yaml" not in bad_files:
        from coach.memory import questions as qmod
        if md != qmod.render_markdown(store.questions()):
            add("warning", "questions_md_stale", "open-questions.md",
                "differs from what open-questions.yaml renders (hand-edited or out of date); it is regenerated by the "
                "next `coach questions` change and a hand-edited copy is saved under .backups/")

    # ---- 3. annotations: categories / events / data
    anns = store.annotations() if "categorization.yaml" not in bad_files else []
    cat_model = None
    if anns and "categorization.yaml" not in bad_files:
        cat_model = store.model("categorization.yaml")
        for i in store.semantic_issues("categorization.yaml", cat_model, strict=False):
            out.append(i)
        used_events = {a.event for a in anns if a.event}
        for e in sorted(store.event_ids() - used_events):
            add("info", "unused_event", "events.md", f"event {e!r} is defined but no annotation refers to it")

    txs = None
    if con is not None:
        txs = txmatch.load_txs(con)
    if con is not None and anns:
        plain = [txmatch.ann_plain(a) for a in anns]
        stats = txmatch.analyse(plain, txs)
        acc_total = Counter(t["account"] for t in txs)
        remap = dict(con.execute("SELECT old_key, new_key FROM tx_key_remap"))
        known_keys = {t["tx_key"] for t in txs}
        for a in anns:
            s = stats[a.id]
            where = f"annotations[{a.id}]"
            if s.matched == 0:
                add("warning", "annotation_matches_nothing", "categorization.yaml",
                    "matches 0 transactions (wrong regex/dates, or the data is not there yet)", where)
            else:
                worst = max(((s.per_account[acc] / acc_total[acc], acc) for acc in s.per_account if acc_total[acc] >= MIN_ACCOUNT_TX),
                            default=(0.0, None))
                if worst[0] > SHARE_WARN:
                    add("warning", "annotation_too_broad", "categorization.yaml",
                        f"matches {worst[0]:.0%} of the transactions of one account ({s.matched} in total): "
                        "is the pattern too wide?", where)
                if s.won == 0:
                    sh = ", ".join(f"{k} ({n})" for k, n in s.shadowed_by.most_common(3))
                    add("warning", "annotation_shadowed", "categorization.yaml",
                        f"never applies: all {s.matched} transactions it matches are taken by an earlier annotation "
                        f"({sh}); the first matching annotation wins, move it up or narrow the earlier one", where)
                elif s.won < s.matched:
                    sh = ", ".join(f"{k} ({n})" for k, n in s.shadowed_by.most_common(3))
                    add("info", "annotation_overlap", "categorization.yaml",
                        f"{s.matched - s.won} of its {s.matched} matches are won by earlier annotations ({sh})", where)
            for k in a.match.tx_keys or []:
                if k in known_keys:
                    continue
                if k in remap:
                    add("warning", "tx_key_remapped", "categorization.yaml",
                        f"tx_key {k!r} was re-keyed to {remap[k]!r} (the old key still matches through the remap log; "
                        "update the annotation)", where)
                else:
                    add("warning", "tx_key_not_found", "categorization.yaml", f"tx_key {k!r} is not in the database", where)

    # ---- 4. liabilities / contracts against payments
    cut6 = qgen.months_ago(today, stale_months)
    for rel, m in store.liabilities():
        crit = [f for f in (("lender", "end_date", "residual_value") if m.kind in ("loa", "lld")
                            else ("lender", "end_date", "outstanding", "rate.nominal")) if qgen._get(m, f) is None]
        if crit:
            add("info", "liability_incomplete", rel, f"critical fields not filled: {', '.join(crit)}")
        if m.outstanding is not None:
            if m.outstanding_as_of is None:
                add("warning", "outstanding_undated", rel, "outstanding capital has no outstanding_as_of date", "outstanding_as_of")
            elif m.outstanding_as_of < cut6:
                add("warning", "stale_fact", rel, f"outstanding capital is from {m.outstanding_as_of} "
                    f"(older than {stale_months} months): update it", "outstanding_as_of")
        _loan_schedule_checks(add, rel, m, today)
        if m.end_date and m.end_date < today:
            add("info", "liability_ended", rel, f"end_date {m.end_date} is in the past: is the liability closed?", "end_date")
        if m.payment_match and txs is not None:
            hits = [t for t in _regex_hits(m.payment_match, txs) if t["amount"] < 0]
            if not hits:
                add("warning", "payment_match_nothing", rel, f"payment_match /{m.payment_match}/ matches 0 payments",
                    "payment_match")
            else:
                amts = [abs(t["amount"]) for t in hits]
                med = statistics.median(amts)
                if m.monthly_payment and abs(med - m.monthly_payment) / m.monthly_payment > AMOUNT_TOLERANCE:
                    add("warning", "payment_amount_mismatch", rel,
                        f"payments matched by payment_match are typically {med:,.2f} EUR (range {min(amts):,.2f}"
                        f"-{max(amts):,.2f}, {len(hits)} payments) but monthly_payment is {m.monthly_payment:,.2f} "
                        f"(more than {AMOUNT_TOLERANCE:.0%} apart: wrong pattern, or the amount changed)", "monthly_payment")
                if len(amts) >= 3 and (max(amts) - min(amts)) / med > AMOUNT_TOLERANCE:
                    add("warning", "payment_amount_spread", rel,
                        f"payment_match catches payments of very different sizes ({min(amts):,.2f} to {max(amts):,.2f} "
                        f"EUR, {len(hits)} payments): the pattern probably also matches another debit", "payment_match")
                for orel, other in store.liabilities():
                    if other.id != m.id and other.payment_match:
                        shared = [t for t in hits if _regex_hits(other.payment_match, [t])]
                        if shared:
                            add("warning", "payment_match_overlap", rel,
                                f"{len(shared)} of its {len(hits)} matched payments are also matched by "
                                f"{other.id} ({orel}): make one of the two patterns more specific", "payment_match")
                last = max(t["date"] for t in hits)
                if (today - dt.date.fromisoformat(last)).days > 75 and not m.end_date:
                    add("info", "payments_stopped", rel, f"last matched payment is {last}: did the loan end?")
    for rel, m in store.contracts():
        if m.renewal and m.renewal < today:
            add("info", "contract_renewal_passed", rel, f"renewal date {m.renewal} has passed: update it", "renewal")
        if m.merchant_match and txs is not None:
            hits = [t for t in _regex_hits(m.merchant_match, txs, desc=False) if t["amount"] < 0]
            if not hits:
                add("warning", "merchant_match_nothing", rel, f"merchant_match /{m.merchant_match}/ matches 0 payments",
                    "merchant_match")
            elif m.billing and m.billing.amount:
                med = statistics.median(abs(t["amount"]) for t in hits)
                if abs(med - m.billing.amount) / m.billing.amount > AMOUNT_TOLERANCE:
                    add("warning", "payment_amount_mismatch", rel,
                        f"payments are typically {med:,.2f} EUR but billing.amount is {m.billing.amount:,.2f}",
                        "billing.amount")

    # ---- 5. assets (E3-8)
    cut_a = qgen.months_ago(today, asset_stale_months)
    for a in store.assets():
        if a.amount is None:
            add("info", "asset_no_value", "assets.yaml", f"asset {a.id} ({a.kind}) has no value yet", f"assets[{a.id}]")
        elif a.as_of is None:
            add("warning", "asset_undated", "assets.yaml", f"asset {a.id} has a value but no as_of date",
                f"assets[{a.id}].as_of")
        elif a.as_of < cut_a:
            add("warning", "stale_value", "assets.yaml",
                f"asset {a.id}: value from {a.as_of} is older than {asset_stale_months} months: update it",
                f"assets[{a.id}].as_of")

    # ---- 5a. rental properties (E15): the links and the commitment the owner recorded
    if "assets.yaml" not in bad_files:
        liab_ids = {m.id for _r, m in store.liabilities()}
        rentals = [a for a in store.assets() if a.kind == "real_estate_rental"]
        for a in rentals:
            if a.loan and a.loan not in liab_ids:
                add("warning", "rental_unknown_loan", "assets.yaml", f"property {a.id}: loan {a.loan!r} is not a loan file in liabilities/",
                    f"assets[{a.id}].loan")
            if a.account and con is not None and not con.execute("SELECT 1 FROM accounts WHERE uid=? OR label=? OR name=?", (a.account,) * 3).fetchone():
                add("warning", "rental_unknown_account", "assets.yaml", f"property {a.id}: account {a.account!r} is not a known account uid or label "
                    "(`coach coverage`)", f"assets[{a.id}].account")
            if a.account and con is not None:
                row = con.execute("SELECT purpose FROM accounts WHERE uid=? OR label=? OR name=?", (a.account,) * 3).fetchone()
                if row and (row[0] or "") != "rental":
                    add("info", "rental_account_purpose", "assets.yaml", f"property {a.id}: its account has purpose {row[0] or 'unset'}, not "
                        "'rental' (`coach accounts set --purpose rental`): the loan instalments are then not labelled to the property", f"assets[{a.id}].account")
            c = a.commitment
            if c and c.start_date and c.start_date > today + dt.timedelta(days=366):
                add("warning", "rental_commitment_future", "assets.yaml", f"property {a.id}: the commitment starts on {c.start_date}, more than a year ahead",
                    f"assets[{a.id}].commitment.start_date")
            if (a.scheme or a.pinel_commitment_years) and not (c and c.start_date):
                add("info", "rental_commitment_start_missing", "assets.yaml", f"property {a.id}: under a scheme but no commitment.start_date: "
                    "the end date and its reminders cannot be computed", f"assets[{a.id}].commitment.start_date")
        if con is not None:
            free = [u for (u,) in con.execute("SELECT uid FROM accounts WHERE exclude=0 AND purpose='rental'")]
            named = {x for a in rentals for x in (a.account,) if x}
            if free and not rentals:
                add("info", "rental_account_without_property", "assets.yaml", f"{len(free)} account(s) have purpose 'rental' but no asset of kind "
                    "real_estate_rental describes the property (`coach rental edit`)")
            elif len(free) > len([a for a in rentals if not a.account]) + len(named) and rentals:
                add("info", "rental_account_without_property", "assets.yaml", "more accounts have purpose 'rental' than properties name an account")

    # ---- 5b. budgets and goals (E4): what they refer to must exist
    if "goals.yaml" not in bad_files:
        asset_ids = {a.id for a in store.assets()}
        labels = set()
        if con is not None:
            labels = {x for uid, lab in con.execute("SELECT uid, label FROM accounts") for x in (uid, lab) if x}
        for g in store.goals():
            if g.asset and g.asset not in asset_ids:
                add("warning", "goal_unknown_asset", "goals.yaml", f"goal {g.id} refers to asset {g.asset!r}, which is not in assets.yaml",
                    f"goals[{g.id}].asset")
            if g.account and con is not None and g.account not in labels:
                add("warning", "goal_unknown_account", "goals.yaml", f"goal {g.id} refers to account {g.account!r}, which is not "
                    "a known account uid or label (`coach coverage`)", f"goals[{g.id}].account")
            if g.target_date and g.target_date < today:
                add("info", "goal_target_passed", "goals.yaml", f"goal {g.id}: the target date {g.target_date} has passed",
                    f"goals[{g.id}].target_date")
    if "budgets.yaml" in store.files() and "budgets.yaml" not in bad_files:
        for i in store.semantic_issues("budgets.yaml", store.model("budgets.yaml"), strict=False):
            out.append(i)                                       # unknown category / group
    if "goals.yaml" in store.files() and "goals.yaml" not in bad_files:
        known_tags = {t for a in store.annotations() for t in a.tags}
        for g in store.goals():
            if g.tag and g.tag not in known_tags:
                add("warning", "goal_unknown_tag", "goals.yaml", f"goal {g.id}: no annotation in categorization.yaml carries the tag "
                    f"{g.tag!r}, so no transaction can feed it", f"goals[{g.id}].tag")
        by_source: dict = {}
        for g in store.goals():
            by_source.setdefault(g.asset or g.account or g.tag, []).append(g.id)
        for src, ids in by_source.items():
            if len(ids) > 1:
                add("warning", "goal_shared_source", "goals.yaml", f"goals {', '.join(ids)} all draw on {src!r}: the same money "
                    "would count for each of them", f"goals[{ids[1]}]")
    if "budgets.yaml" not in bad_files:
        seen_targets: dict = {}
        owners = {m.id for m in store.members()} | {"joint"}
        for b in store.budgets():
            key = (b.category, b.group, b.owner, b.account)
            if key in seen_targets:
                add("warning", "budget_duplicate", "budgets.yaml", f"budget {b.id} has the same target and scope as "
                    f"{seen_targets[key]}: the two envelopes would count the same spending twice", f"budgets[{b.id}]")
            seen_targets[key] = b.id
            if b.owner and store.members() and b.owner not in owners:
                add("warning", "budget_unknown_owner", "budgets.yaml", f"budget {b.id}: owner {b.owner!r} is neither 'joint' "
                    "nor a household member", f"budgets[{b.id}].owner")

    # ---- 6. household members vs accounts
    members = store.members() if "household.yaml" not in bad_files else []
    if members and "household.yaml" not in bad_files:                    # E14: rules naming members / categories that do not exist
        for i in store.semantic_issues("household.yaml", store.model("household.yaml"), strict=False):
            out.append(i)
        hh_model = store.model("household.yaml")
        if hh_model is not None:
            if hh_model.members and not any(m.role == "adult" for m in hh_model.members):
                add("warning", "household_no_adult", "household.yaml", "no adult member is declared")
            for r in hh_model.attribution:
                if r.match.account and con is not None and not con.execute(
                        "SELECT 1 FROM accounts WHERE uid=? OR label=? OR name=?", (r.match.account,) * 3).fetchone():
                    add("warning", "attribution_unknown_account", "household.yaml",
                        f"attribution rule {r.id}: account {r.match.account!r} is not a known account uid or label", f"attribution[{r.id}].match.account")
    for m in members:
        if m.birth_year is None:
            add("info", "member_no_birth_year", "household.yaml", f"member {m.id} has no birth_year", f"members[{m.id}]")
    if con is not None:
        owners = Counter(o for (o,) in con.execute("SELECT owner FROM accounts WHERE owner IS NOT NULL AND exclude=0"))
        if members:
            known = {m.id.lower() for m in members} | {m.name.lower() for m in members} | \
                    {a.lower() for m in members for a in m.aliases}
            for o, n in owners.items():
                if o.lower() != "joint" and o.lower() not in known:
                    add("warning", "owner_not_a_member", "household.yaml",
                        f"{n} account(s) have owner {o!r}, who is not a member (id, name or alias) of household.yaml")
        elif owners and not store.exists("household.yaml"):
            add("info", "no_household", "household.yaml",
                f"missing: {len(owners)} account owner value(s) exist but no household is declared "
                "(`coach memory member add`)")
        nopurpose = con.execute("SELECT COUNT(*) FROM accounts WHERE exclude=0 AND (owner IS NULL OR purpose IS NULL)").fetchone()[0]
        if nopurpose:
            add("info", "accounts_incomplete", "accounts", f"{nopurpose} account(s) without owner or purpose "
                "(`coach accounts set`)")

    # ---- 7. open questions whose subject has been resolved since
    for q in store.questions():
        why = qgen.resolved_reason(q, store, con, cfg)
        if why:
            add("info", "question_resolved", "open-questions.yaml",
                f"{q.id} is still open but looks resolved ({why}): answer or dismiss it", f"questions[{q.id}]")

    # ---- 8a. document links: files named in `documents:` must exist; files in documents/ must be recorded
    recorded = {d.stored_as for d in store.documents()}
    for rel, m in [*store.liabilities(), *store.contracts()]:
        for ref in m.documents:
            try:
                present = store.exists(ref)
            except Exception:                                        # noqa: BLE001
                present = False
            if not present:
                add("warning", "document_link_dangling", rel, f"documents: {ref!r} does not exist (a reverted or deleted "
                    "`memory doc add`?)", "documents")
    ddir = store.root / "documents"
    if store._dir_usable("documents"):
        for f in sorted(ddir.iterdir()):
            if f.is_file() and f.name not in recorded and not f.name.endswith(".part"):
                add("warning", "document_orphan", "documents.yaml", f"documents/{f.name} is not recorded in documents.yaml "
                    "(a reverted `memory doc add`?): delete the file or record it again")

    # ---- 8. documents
    for d in store.documents():
        p = store.root / "documents" / d.stored_as
        if not p.exists():
            add("error", "document_missing", "documents.yaml", f"{d.id}: stored file {d.stored_as} is missing", f"documents[{d.id}]")
        else:
            import hashlib
            if hashlib.sha256(p.read_bytes()).hexdigest() != d.sha256:
                add("error", "document_corrupt", "documents.yaml", f"{d.id}: content does not match its sha256",
                    f"documents[{d.id}]")
        if d.for_id and not any(d.for_id == x for x in _all_ids(store)):
            add("warning", "document_target_missing", "documents.yaml", f"{d.id}: refers to {d.for_id!r}, which does not exist",
                f"documents[{d.id}].for")

    # ---- 9. quasi-identifiers a model must not learn: the employer and the towns are masked only when declared
    if store.exists("household.yaml") and "household.yaml" not in bad_files:
        try:
            hh = store.load_plain("household.yaml") or {}
        except Exception:                                                  # noqa: BLE001
            hh = {}
        salary = False
        if con is not None:
            try:
                salary = bool(con.execute("SELECT 1 FROM merchants WHERE category='income.salary' LIMIT 1").fetchone())
            except Exception:                                              # noqa: BLE001
                salary = False
        if salary and not [e for e in (hh.get("employers") or []) if isinstance(e, str) and e.strip()]:
            add("warning", "employer_not_declared", "household.yaml", "salary income exists but no employer is declared: "
                "add `employers: [...]` so that the employer's name is masked in everything a model sees ([employer])", "employers")
        if con is not None and not [p for p in (hh.get("places") or []) if isinstance(p, str) and p.strip()]:
            add("warning", "places_not_declared", "household.yaml", "no home / work towns are declared: add `places: [...]` so that "
                "they are masked in everything a model sees ([place])", "places")

    out.sort(key=lambda i: (LEVELS[i.level], i.file, i.path))
    return out


def _all_ids(store: MemoryStore) -> set[str]:
    return {m.id for _, m in store.liabilities()} | {m.id for _, m in store.contracts()} | {a.id for a in store.assets()}


def format_issues(issues: list[Issue]) -> str:
    if not issues:
        return "memory check: no findings"
    lines = []
    for i in issues:
        loc = i.file + (f":{i.line}" if i.line else "") + (f" {i.path}" if i.path else "")
        lines.append(f"{i.level.upper():<7} {i.code:<26} {loc}\n        {i.message}")
    s = summarize(issues)
    lines.append(f"\n{s['errors']} error(s), {s['warnings']} warning(s), {s['info']} info")
    return "\n".join(lines)
