"""Open questions (E3-3): the structured store ``open-questions.yaml`` and its human view ``open-questions.md``.

The YAML is the source of truth; the Markdown is regenerated after every change (a hand edit of the Markdown is
backed up to ``.backups/`` before it is overwritten). Answering a question only RECORDS the answer; turning it into
memory changes (annotation, liability fields...) is a separate, previewed step (``coach memory annotate`` / ``set``).
"""
from __future__ import annotations

import datetime as dt
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from coach.memory import schemas, yamlio
from coach.memory.store import EditResult, MemoryStore, MemoryStoreError

YAML_FILE = "open-questions.yaml"
MD_FILE = "open-questions.md"
HEADER = """# Open questions for the user

<!-- Generated from open-questions.yaml by `coach questions`: do not edit this file by hand (it is rewritten;
     a hand-edited copy is saved under .backups/). Use `coach questions answer|dismiss|add` instead. -->

The coach asks these when relevant. An answer is recorded here first, then turned into concrete changes of the
other memory files (`categorization.yaml`, `events.md`, `liabilities/`, `contracts/`, `assets.yaml`...).
"""


class QuestionError(MemoryStoreError):
    pass


def _fmt_ev(ev: dict) -> str:
    parts = []
    for k, v in ev.items():
        if isinstance(v, list):
            v = ",".join(str(x) for x in v)
        parts.append(f"{k}={v}")
    return "; ".join(parts)


def render_line(q: schemas.Question) -> str:
    tag = f"`{q.id}`"
    if q.status == "answered":
        if q.origin == "migrated" and q.source_text and q.answer and q.answer == legacy_answer(q.source_text):
            return f"- [x] {tag} {q.source_text}"
        when = f" (answered {q.answered})" if q.answered else ""
        return f"- [x] {tag} {q.question} → {q.answer}{when}"
    if q.status == "dismissed":
        why = f": {q.note}" if q.note else ""
        return f"- [-] {tag} ~~{q.question}~~ (dismissed{(' ' + str(q.answered)) if q.answered else ''}{why})"
    extra = ""
    if q.origin == "migrated" and q.source_text:
        return f"- [ ] {tag} {q.source_text}"
    if q.evidence:
        extra += f" ({_fmt_ev(q.evidence)})"
    if q.suggested_target:
        extra += f" → `{q.suggested_target.file}`" + (f" `{q.suggested_target.field}`" if q.suggested_target.field else "")
    text = q.source_text if q.origin == "migrated" and q.source_text else q.question
    return f"- [ ] {tag} {text}{extra}"


def render_markdown(questions: list[schemas.Question]) -> str:
    out = [HEADER]
    topics: list[str] = []
    for q in questions:
        if q.topic not in topics:
            topics.append(q.topic)
    n_open = sum(q.status == "open" for q in questions)
    out.append(f"{n_open} open, {sum(q.status == 'answered' for q in questions)} answered, "
               f"{sum(q.status == 'dismissed' for q in questions)} dismissed.\n")
    for t in topics:
        out.append(f"## {t}\n")
        out += [render_line(q) for q in questions if q.topic == t]
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------- legacy markdown -> structured (migrate)

ITEM_RE = re.compile(r"^-\s+\[( |x|X)\]\s+(.*)$")
PLAIN_RE = re.compile(r"^-\s+(?!\[)(.*)$")
ANSWERED_RE = re.compile(r"\((?:answered\s+)?(\d{4}-\d{2}-\d{2})\)\.?\s*$")
TARGET_RE = re.compile(r"→\s*`([A-Za-z0-9_./-]+\.(?:yaml|md))`")
STAKE_RE = re.compile(r"([\d][\d,]*(?:\.\d+)?)\s*EUR")


@dataclass
class MigrationPlan:
    questions: list[schemas.Question]
    ignored: list[str]            # non-empty lines that are not questions (title, intro)
    n_open: int
    n_answered: int
    md_items: int                 # checkbox items found in the Markdown

    @property
    def lossless(self) -> bool:
        return len(self.questions) == self.md_items


def parse_legacy(text: str) -> tuple[list[dict], list[str]]:
    topic, items, ignored = "General", [], []
    cur = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.startswith("## "):
            topic, cur = line[3:].strip(), None
            continue
        m = ITEM_RE.match(line)
        p = None if m else PLAIN_RE.match(line)
        if m or p:
            cur = {"topic": topic, "checked": bool(m and m.group(1) in "xX"), "text": (m.group(2) if m else p.group(1)).strip()}
            items.append(cur)
        elif cur is not None and line.startswith((" ", "\t")) and line.strip():
            cur["text"] += " " + line.strip()
        else:
            if line.strip():
                ignored.append(line.strip())
            cur = None
    return items, ignored


def plan_migration(md_text: str, today: Optional[dt.date] = None) -> MigrationPlan:
    items, ignored = parse_legacy(md_text)
    qs: list[schemas.Question] = []
    for n, it in enumerate(items, 1):
        text = it["text"]
        answered_on = None
        clean = text
        m = ANSWERED_RE.search(text)
        if it["checked"] and m:
            answered_on = dt.date.fromisoformat(m.group(1))
            clean = text[:m.start()].rstrip()
        lead = re.match(r"^\*\*(.+?)\*\*", clean)
        target = TARGET_RE.findall(text)
        amounts = [float(x.replace(",", "")) for x in STAKE_RE.findall(text) if x.replace(",", "").replace(".", "", 1).isdigit()]
        common = dict(id=f"q-{n:03d}", topic=it["topic"], origin="migrated", source_text=text,
                      suggested_target={"file": target[-1]} if target else None,
                      stake=max(amounts) if amounts and not it["checked"] else None)
        if it["checked"]:
            subject = lead.group(1) if lead else (clean[:80] + ("..." if len(clean) > 80 else ""))
            qs.append(schemas.Question(status="answered", question=subject, answer=clean, answered=answered_on,
                                       **common))
        else:
            qs.append(schemas.Question(status="open", question=clean, **common))
    return MigrationPlan(qs, ignored, sum(q.status == "open" for q in qs), sum(q.status == "answered" for q in qs),
                         len(items))


def legacy_answer(source_text: str) -> str:
    """The answer a migrated checked item carries: its line without the trailing `(answered DATE)`."""
    m = ANSWERED_RE.search(source_text)
    return source_text[:m.start()].rstrip() if m else source_text


def questions_to_doc(questions: list[schemas.Question]) -> dict:
    out = []
    for q in questions:
        d = q.model_dump(mode="python", exclude_none=True, by_alias=True)
        if not d.get("evidence"):
            d.pop("evidence", None)
        if q.suggested_target:
            d["suggested_target"] = q.suggested_target.model_dump(exclude_none=True)
        # a stable, readable key order
        order = ["id", "status", "topic", "question", "context", "evidence", "suggested_target", "stake", "key",
                 "origin", "created", "answered", "answer", "note", "source_text"]
        out.append({k: d[k] for k in order if k in d})
    return {"questions": out}


FILE_HEADER = ("# Open questions (source of truth). The Markdown view open-questions.md is generated from this file.\n"
               "# Manage them with `coach questions list|answer|dismiss|add|generate`.\n")


def backup_file(store: MemoryStore, rel: str, now: Optional[dt.datetime] = None) -> Optional[Path]:
    src = store.path(rel)
    if not src.exists():
        return None
    now = now or dt.datetime.now()
    dest = store.root / ".backups" / f"{Path(rel).name}.{now.strftime('%Y%m%d-%H%M%S')}"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.parent.chmod(0o700)
    n = 0
    while dest.exists():
        n += 1
        dest = dest.with_name(f"{dest.name}.{n}")
    shutil.copy2(src, dest)
    dest.chmod(0o600)
    return dest


def migrate_preview(store: MemoryStore) -> tuple[MigrationPlan, str]:
    if store.exists(YAML_FILE):
        raise QuestionError(f"{YAML_FILE} already exists: the migration was done (or the file was created by hand)")
    if not store.exists(MD_FILE):
        raise QuestionError(f"{MD_FILE} does not exist: nothing to migrate")
    plan = plan_migration(store.read_text(MD_FILE))
    if not plan.lossless:
        raise QuestionError(f"internal check failed: {plan.md_items} items in the Markdown but {len(plan.questions)} parsed")
    return plan, render_markdown(plan.questions)


def migrate_write(store: MemoryStore) -> tuple[MigrationPlan, Optional[Path], EditResult]:
    plan, new_md = migrate_preview(store)
    backup = backup_file(store, MD_FILE)
    doc = yamlio.dumps(_doc(questions_to_doc(plan.questions)))
    res = store.write_text(YAML_FILE, FILE_HEADER + doc, action="migrate-questions", source=None,
                           reason="open-questions.md converted to structured open-questions.yaml",
                           extra_files={MD_FILE: new_md})
    return plan, backup, res


def _doc(data: dict):
    from coach.memory.edit import to_rt
    return to_rt(data)


# ---------------------------------------------------------------- service

def _companion(store: MemoryStore):
    def make(model):
        return {MD_FILE: render_markdown(model.questions)}
    return make


def md_hand_edited(store: MemoryStore) -> bool:
    """The Markdown is a generated view: True if it differs from what the CURRENT yaml renders (someone edited it, or
    it is out of date)."""
    return store.exists(MD_FILE) and store.exists(YAML_FILE) and store.read_text(MD_FILE) != render_markdown(store.questions())


def _refuse_if_hand_edited(store: MemoryStore) -> None:
    if md_hand_edited(store):
        raise QuestionError(
            f"{MD_FILE} was edited by hand (or is out of date): those edits are NOT in {YAML_FILE} and the next write "
            "would overwrite them. See what differs with `coach memory diff open-questions.md`; move anything that "
            "matters with `coach questions add|answer|dismiss`, then `coach questions regenerate-view` "
            "(saves your edited copy under .backups/ and rewrites the view)")


def regenerate_view(store: MemoryStore, source: Optional[str] = None) -> Optional[Path]:
    """Rewrite open-questions.md from the yaml after saving the hand-edited copy; returns the backup path."""
    if not store.exists(YAML_FILE):
        raise QuestionError(f"{YAML_FILE} does not exist")
    backup = backup_file(store, MD_FILE) if md_hand_edited(store) else None
    store.write_text(YAML_FILE, store.read_text(YAML_FILE), action="regenerate-questions-view", source=source,
                     extra_files={MD_FILE: render_markdown(store.questions())})
    return backup


def _get(store: MemoryStore, qid: str) -> schemas.Question:
    for q in store.questions():
        if q.id == qid:
            return q
    ids = [q.id for q in store.questions()]
    raise QuestionError(f"no question {qid!r}" + (f" (e.g. {', '.join(ids[:5])})" if ids else " (run `coach questions generate` or `add`)"))


def _edit(store: MemoryStore, ops: list[dict], action: str, reason: Optional[str], source: Optional[str], create: bool = False):
    _refuse_if_hand_edited(store)
    if not store.exists(YAML_FILE):
        base = {"questions": []}
        res = store.edit(YAML_FILE, [{"op": "create", "value": base}] + ops, action=action, reason=reason, source=source,
                         companion=_companion(store))
    else:
        res = store.edit(YAML_FILE, ops, action=action, reason=reason, source=source, companion=_companion(store))
    return res


def add(store: MemoryStore, question: str, *, topic: str = "General", target: Optional[str] = None,
        evidence: Optional[dict] = None, key: Optional[str] = None, qid: Optional[str] = None,
        origin: str = "manual", stake: Optional[float] = None, context: Optional[str] = None,
        today: Optional[dt.date] = None, source: Optional[str] = None) -> schemas.Question:
    existing = {q.id for q in store.questions()}
    if not qid:
        n = 1
        while f"q-{n:03d}" in existing:
            n += 1
        qid = f"q-{n:03d}"
    if qid in existing:
        raise QuestionError(f"question {qid!r} already exists")
    tgt = None
    if target:
        f, _, fld = target.partition(":")
        tgt = {"file": f, **({"field": fld} if fld else {})}
    q = schemas.Question(id=qid, question=question, topic=topic, evidence=evidence or {}, suggested_target=tgt,
                         created=today or dt.date.today(), key=key, origin=origin, stake=stake, context=context)
    _edit(store, [{"op": "append", "path": "questions", "value": questions_to_doc([q])["questions"][0]}],
          "add-question", None, source)
    return q


def add_many(store: MemoryStore, qs: list[schemas.Question], source: Optional[str] = None) -> None:
    if not qs:
        return
    ops = [{"op": "append", "path": "questions", "value": d} for d in questions_to_doc(qs)["questions"]]
    _edit(store, ops, "generate-questions", f"{len(qs)} question(s) generated from the data", source)


def answer(store: MemoryStore, qid: str, text: str, *, today: Optional[dt.date] = None, source: Optional[str] = None) -> schemas.Question:
    q = _get(store, qid)
    if q.status == "answered":
        raise QuestionError(f"{qid} is already answered; `coach questions reopen {qid}` first to change the answer")
    if not text.strip():
        raise QuestionError("the answer is empty")
    ops = [{"op": "set", "path": f"{qid}.status", "value": "answered"},
           {"op": "set", "path": f"{qid}.answer", "value": text.strip()},
           {"op": "set", "path": f"{qid}.answered", "value": today or dt.date.today()}]
    if q.note:
        ops.append({"op": "unset", "path": f"{qid}.note"})
    _edit(store, ops, "answer-question", qid, source)
    return _get(store, qid)


def dismiss(store: MemoryStore, qid: str, reason: Optional[str] = None, *, today: Optional[dt.date] = None,
            source: Optional[str] = None) -> schemas.Question:
    q = _get(store, qid)
    if q.status == "dismissed":
        return q
    if q.status == "answered":
        raise QuestionError(f"{qid} is answered; reopen it first")
    ops = [{"op": "set", "path": f"{qid}.status", "value": "dismissed"},
           {"op": "set", "path": f"{qid}.answered", "value": today or dt.date.today()}]
    if reason:
        ops.append({"op": "set", "path": f"{qid}.note", "value": reason})
    _edit(store, ops, "dismiss-question", qid, source)
    return _get(store, qid)


def reopen(store: MemoryStore, qid: str, source: Optional[str] = None) -> schemas.Question:
    q = _get(store, qid)
    if q.status == "open":
        return q
    ops = [{"op": "set", "path": f"{qid}.status", "value": "open"}]
    for f in ("answer", "answered", "note"):
        if getattr(q, f):
            ops.append({"op": "unset", "path": f"{qid}.{f}"})
    _edit(store, ops, "reopen-question", qid, source)
    return _get(store, qid)


def listing(store: MemoryStore, status: Optional[str] = None) -> list[schemas.Question]:
    qs = store.questions()
    if status:
        qs = [q for q in qs if q.status == status]
    return sorted(qs, key=lambda q: (q.status != "open", -(q.stake or 0)))
